language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - apt-get install libjpeg-dev
    - pip install -r requirements.txt
    - pip install -r requirements-devel.txt
script: ./run_tests.sh