language: python
python:
  - "3.3"
  - "2.7"
before_install:
    - sudo apt-get install libjpeg-dev
install:
    - pip install -r requirements.txt
    - pip install -r requirements-devel.txt
script: ./run_tests.sh